### ISSUE TITLE
failed to run "./run_jupyter.sh" script

### ISSUE THREAD

**Issue by evgenysushko** [hamelsmu/Docker_Tutorial#5]
While following your tutorial and creating a container I ran into the following error:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./run_jupyter.sh\": stat ./run_jupyter.sh: no such file or directory": unknown.`

I'm running Docker for mac, version 18.03.1-ce-mac65

**Comment by hamelsmu** [comment]
Its looking for the `run_jupyter.sh` file in this repo:  https://github.com/hamelsmu/docker-cpu

**Comment by evgenysushko** [comment]
Why should it look for the `run_jupyter.sh` in that repo?  I don't see any reference to https://github.com/hamelsmu/docker-cpu in the `Dockerfile`

**Comment by hamelsmu** [comment]
run_jupyter.sh is  mentioned explicitly in the Dockerfile.  It’s not looking for the file in the repo it’s looking for the file in your local system when it does the ADD command.  You can get the file from the repo.  The ADD statement is mentioned in the blog post.

**Comment by evgenysushko** [comment]
It was not clear for me which location is considered to be the context directory. Now it's clear that it is specified when the container is run. Thanks!
